Fix AttributeError: 'float' object has no attribute 'denominator'
This error occurred when f1 returned float('nan') instead of a Ratio.
Since Ratio.__truediv__ takes care of a zero denominator, the if is not
needed.